# Generated by Django 4.2.7 on 2023-11-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_options_carmodel_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
    ]
