# Generated by Django 4.2.7 on 2023-12-17 15:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparksmodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='autoparksmodel',
            name='owners',
            field=models.ManyToManyField(related_name='auto_parks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autoparksmodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1,20}$', 'Only letters min 1 max 20 ch')]),
        ),
    ]
